### ISSUE TITLE
How to create empty array

### ISSUE THREAD

**Issue by nirenrc** [tidwall/sjson#15]
Hello

I would like to create empty array, could not find working syntax using "Set" API. e,g. to achieve below json
{
	"home": {
		"kitchen": {
			"refrigerator": []
		}
	}
}

what would be path syntax in Set API or any other to achieve same?

Niren

**Comment by tidwall** [comment]
Hi, try the `SetRaw` function.

```
sjson.SetRaw(json, "home.kitchen.refridgerator", "[]")
```

**Comment by nirenrc** [comment]
Thank You

Yes, it works. Other option of "-1" works too  
sjson.SetRaw(json, "home.kitchen.refridgerator.-1", "")

Niren
