### ISSUE TITLE
Delete not reliable

### ISSUE THREAD

**Issue by lc-jordanfelix** [tidwall/sjson#21]
Occasionally when we delete a field, the function deletes the field before, in addition to the intended field.

A demonstration unit test is attached of the function sjson.Delete
[sjson_test.go.zip](https://github.com/tidwall/sjson/files/2381481/sjson_test.go.zip)

**Comment by richardardrichard** [comment]
Hey @lc-jordanfelix the issue only seemed to be occurring for me when I had extra whitespace in the source string. I probably shouldn't have closed the original issue, but this was not an issue for me in any sort of real-world scenario.

**Comment by lc-jordanfelix** [comment]
Ah, well for us it happened in production with the JSON below where the date_created field is incorrectly deleted when we delete the date_updated field:

```json
[{"country_code_from":"NZ","country_code_to":"SA","date_created": "2018-09-13T02:56:11.25783Z","date_updated": "2018-09-14T03:15:16.67356Z","disabled":false,"last_edited_by":"Developers","id":"a3e...bc454","merchant_id":"f2b...b91abf","signed_date":"2018-02-01T00:00:00Z","start_date":"2018-03-01T00:00:00Z","url":"https://www.google.com"}]
```

**Comment by tidwall** [comment]
I just pushed a fix. Thanks a ton for reporting!
