### ISSUE TITLE
Reduce Memory allocation using strings.Builder

### ISSUE THREAD

**Issue by rosspatil** [tidwall/sjson#27]
As this library is currently using append which cost huge in terms of memory allocation. If we introduce strings.Builder instead of append, allocation will drastically reduce.

**Comment by tidwall** [comment]
Thank you for your interest in making sjson better, and I'm always happy to explore ways to make any of my projects faster.

In my experience `append` is one of the more efficient ways to auto-grow and copy bytes in golang. 

As I understand string.Builder is mostly a friendly wrapper for `append`, with also the addition of a zero-cost `[]bytes` -> `string` using an unsafe cast.

```
func (b *Builder) WriteString(s string) (int, error) {
	b.copyCheck()
	b.buf = append(b.buf, s...)
	return len(s), nil
}

func (b *Builder) String() string {
	return *(*string)(unsafe.Pointer(&b.buf))
}
```

I must be missing something. Please elaborate further.
