### ISSUE TITLE
Question on behavior of sjson

### ISSUE THREAD

**Issue by santoshaitha** [tidwall/sjson#29]
can you explain the behavior of below code?

https://play.golang.org/p/0GkEaE0hdq1

the given code is giving output as 

$go run main.go
JSON:{"node":"{\"name\":\"xxxx\"}"}
JSON1:{"node":"{\"childs\":[{\"lastname\":\"yyyyy\"}]"}

it is replacing the string output got from line#10. 

if i change the line#16 and use the hardcoded string "{"node":"{\"name\":\"xxxx\"}"}" in place newjson then it is returning the output as below.

{"node":"{\"childs\":[{\"lastname\":\"yyyyy\"}],\"name\":\"xxxx\""}

**Comment by tidwall** [comment]
In your program:

```go
package main

import (
	"fmt"

	"github.com/tidwall/sjson"
)

func main() {
	newjson, err := sjson.Set("", "node", `{"name":"xxxx"}`)
	if err != nil {
		fmt.Errorf("NEW JSON ERRRO :%v", err)
		return
	}
	fmt.Printf("JSON:%s \n", newjson)
	newjson1, err := sjson.SetRaw(newjson, "node", `{"childs":[{"lastname":"yyyy"}]`)
	if err != nil {
		fmt.Errorf("NEW JSON1 ERRRO :%v", err)
		return
	}
	fmt.Printf("JSON1:%s \n", newjson1)
}
```

The line ...

```
sjson.Set(newjson, "node", `{"childs":[{"lastname":"yyyy"}]`)
```

... is interpreted as `assign the third arg (string value) to json member "node"`.
The third arg in the `Set()` function automatically translates the Go type (int, string, bool, etc) into a valid JSON type. It's literally taking your Go string and translating it to a JSON string.

You probably looking for `SetRaw` which will not translate the third arg.

```
sjson.SetRaw(newjson, "node", `{"childs":[{"lastname":"yyyy"}]`)
```

**Comment by santoshaitha** [comment]
I am trying to expect the output of statement: 
sjson.Set(newjson, "node", `{"childs":[{"lastname":"yyyy"}]`)

output:
{"node":"{"childs":[{"lastname":"yyyyy"}],"name":"xxxx""}

 i am trying to append childs array to existing newjson value. But the Set or SetRaw functions both replacing the existing value in newjson string variable.

**Comment by tidwall** [comment]
Please provide the json that you are expecting.

**Comment by tidwall** [comment]
The program:
```go
ackage main

import (
	"fmt"

	"github.com/tidwall/sjson"
)

func main() {
	newjson, err := sjson.SetRaw("", "node", `{"name":"xxxx"}`)
	if err != nil {
		fmt.Errorf("NEW JSON ERRRO :%v", err)
		return
	}
	fmt.Printf("JSON:%s \n", newjson)
	newjson1, err := sjson.SetRaw(newjson, "node", `{"childs":[{"lastname":"yyyy"}]`)
	if err != nil {
		fmt.Errorf("NEW JSON1 ERRRO :%v", err)
		return
	}
	fmt.Printf("JSON1:%s \n", newjson1)

}
```

outputs:

```
JSON:{"node":{"name":"xxxx"}}
JSON1:{"node":{"childs":[{"lastname":"yyyy"}]}
```

**Comment by santoshaitha** [comment]
i am expecting output as --> {"node":"{"childs":[{"lastname":"yyyyy"}],"name":"xxxx""}. i am not worried about about escaping the string.

**Comment by santoshaitha** [comment]
the newjson variable already have value {"name":"xxxx"} and am trying to add a new key "childs" to that json string. but Set function is replacing the value altogether

**Comment by tidwall** [comment]
sjson does not work the way you thinking it should.

The value of "node" in the following json is string, not an object.

```json
 {"node":"{\"childs\":[{\"lastname\":\"yyyyy\"}],\"name\":\"xxxx\""}
```

sjson can only modify members in a JSON object or array.

The `SetRaw` is a special function that provides the ability to set a raw block of json to any member.

A standard way to use sjson would be:

```go
package main

import (
	"fmt"

	"github.com/tidwall/sjson"
)

func main() {
	newjson, err := sjson.Set("", "node.name", "xxx")
	if err != nil {
		fmt.Errorf("NEW JSON ERRRO :%v", err)
		return
	}
	fmt.Printf("JSON:%s \n", newjson)
	newjson1, err := sjson.Set(newjson, "node.childs.0.lastname", "yyyy")
	if err != nil {
		fmt.Errorf("NEW JSON1 ERRRO :%v", err)
		return
	}
	fmt.Printf("JSON1:%s \n", newjson1)
}

// Outputs:
// JSON:{"node":{"name":"xxx"}}
// JSON1:{"node":{"childs":[{"lastname":"yyyy"}],"name":"xxx"}}

```

outputs:

```
```

**Comment by santoshaitha** [comment]
Thank you for clarifications.

**Comment by tidwall** [comment]
My pleasure.

**Comment by santoshaitha** [comment]
One more question: 

what if we want to set multiple keys in to childs.0 like 

childs: [{
"lastname":"yyy",
"city":"ssss"
}
]

Do we need to run sjons.Set on each key in childs.0 object?

like 
newjson1, err := sjson.Set(newjson, "node.childs.0.lastname", "yyyy")
	if err != nil {
		fmt.Errorf("NEW JSON1 ERRRO :%v", err)
		return
	}
newjson1, err := sjson.Set(newjson1, "node.childs.0.city", "xxx")
	if err != nil {
		fmt.Errorf("NEW JSON1 ERRRO :%v", err)
		return
	}

**Comment by tidwall** [comment]
Yes. One Set for each json value.
