### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by nkev** [tidwall/sjson#3]
I (and probably many others) would love to see some benchmarks compared to other libraries, like you did with gjson. Thanks!

**Comment by tidwall** [comment]
I could probably put some benchmarks together. Are there specific libraries for comparison that you would recommend?

**Comment by nkev** [comment]
Just the usual popular ones, maybe: 

`encoding/json`
`pquerna/ffjson`
`mailru/easyjson`
`buger/jsonparser`

Also, I currently use `valyala/fasttemplate` which like `tidwall/sjson`, replaces tokens in text. It is crazy fast, particularly the `ExecuteFunc()` method. I would throw that in the benchmarks too.

Thanks for doing this.

**Comment by tidwall** [comment]
That looks like a good start.

**Comment by Akagi201** [comment]
Maybe you can add this lib which I am using for a long time.

https://github.com/Jeffail/gabs

**Comment by tidwall** [comment]
I finally got around to adding [benchmarks](https://github.com/tidwall/sjson#performance).
I looked into the `valyala/fasttemplate` library, but it wasn't immediately clear how to use it. If you could point me to an example of how to use it with JSON, I'll add a benchmark.

**Comment by tidwall** [comment]
I'm closing this issue for now. Thanks.

**Comment by nkev** [comment]
Thank you for doing the benchmarks. Great Gophercon talk BTW! I hope you get a lot of value out of it for the Tile38 product.

**Comment by tidwall** [comment]
Thanks :)
