### ISSUE TITLE
Confusing doc for ReplaceInPlace field of Options

### ISSUE THREAD

**Issue by wI2L** [tidwall/sjson#4]
Per the doc, regarding the `ReplaceInPlace` field of the `Options` struct :

> There is no guarentees that the memory will be replaced in-place.

I first found this sentence strange, then goes to read the code (https://github.com/tidwall/sjson/blob/master/sjson.go#L413), and I think it could be better expressed, explaining that if the destination slice doesn't have enough free bytes to replace the data in place, a new bytes slice will be created under the hood.

**Comment by tidwall** [comment]
I agree, that's a horrible sentence. "There is no guarentees.." I didn't even use correct grammar. 😬 

I'll update is based on your wording.

**Comment by wI2L** [comment]
@tidwall I always misspell alot writing code doc, and it's even worst as a non native speaker. I don't know which editor you are using and/or linter, but there is the misspell linter (https://github.com/client9/misspell) with gometalinter (https://github.com/alecthomas/gometalinter) that you can enable, it helps alot !

**Comment by tidwall** [comment]
Thanks for the tip. I like the simplicity of https://github.com/client9/misspell.
