### ISSUE TITLE
v1.2.0 breaks updating keys beginning with @

### ISSUE THREAD

**Issue by arigon** [tidwall/sjson#53]
Hello

version 1.2.0+ which added "updates of complex paths" breaks updating keys beginning with the @ symbol.

Example:
```
data, err := sjson.SetBytes([]byte(`{"Test":123}`), "@timestamp", time.Now().Unix())
if err != nil {
	log.Fatal(err)
}
```

Current Result:
`{"Test":123}`

Expected:
`{"Test":123,"@timestamp":1639152890}`

Is there a workaround?

**Comment by tidwall** [comment]
Hi,

The `@` symbol is one of the [reserved character](https://github.com/tidwall/gjson/blob/master/SYNTAX.md#path-structure). The workaround is to [escape it](https://github.com/tidwall/gjson/blob/master/SYNTAX.md#escape-character) with a `\` character.

```go
// Using either one of these styles
sjson.SetBytes([]byte(`{"Test":123}`), "\\@timestamp", time.Now().Unix())
sjson.SetBytes([]byte(`{"Test":123}`), `\@timestamp`, time.Now().Unix())
```

**Comment by arigon** [comment]
Thank you!
