### ISSUE TITLE
How to add map to root of JSON?

### ISSUE THREAD

**Issue by AuroraTea** [tidwall/sjson#74]
```go
origin := {"a":"a"}
new, err := sjson.Set(origin, "", map[string]any{
	"b": "b",
})
```
Expect:  `{"a":"a","b":"b"}`
but give me an error `path cannot be empty`

What is the correct way to write it?

**Comment by natenho** [comment]
@AuroraTea you may take a look at #69, it is the same use case.

**Comment by AuroraTea** [comment]
@natenho Thanks!!!
