### ISSUE TITLE
Feature request: Querying Path

### ISSUE THREAD

**Issue by omani** [tidwall/sjson#8]
Hi,

like in gjson:
```
name := gjson.Get(json, `programmers.#[lastName="Hunter"].firstName`)
println(name.String())  // prints "Elliotte"
```

It would be nice if one could set a field by querying for it. because right now I would like to update an object within an array. and I don't know the index beforehand.

any plans to implement this?

**Comment by omani** [comment]
another approach would be to have a method on gjson to get the index of the found element (from above name's methods). then I could easily update via sjson by giving an index integer/string.

**Comment by omani** [comment]
just found out that there is a method for getting the index position. seems to be ```name.Int()```.

you can consider this issue as closed. but querying a path would be nice nevertheless.

**Comment by tidwall** [comment]
Hi @omani,

I wrote the https://github.com/tidwall/sjson library that can be used for updating values. Though some paths, such as ones that have '#' character may not be updatable.

**Comment by tidwall** [comment]
Sorry about the weird response. I thought this issue was filed on the `gjson` project.

**Comment by tidwall** [comment]
This would be a pretty nice feature and something I'll keep in mind for a future release.

**Comment by omani** [comment]
thanks for the quick response. yeah hope to see it sometime. the ```Int()``` method did the job for me for now.

thanks.

**Comment by tidwall** [comment]
Glad to hear 👍

**Comment by omani** [comment]
I realized method ```Int()``` is not the way to go here. new issue is https://github.com/tidwall/gjson/issues/41.
